class Score < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('score_date DESC') }
	validates :user_id, presence: true
	validates :score_date, presence: true


	def self.to_csv
    CSV.generate do |csv|
      csv << %w{id user_id score_date hc score_1 fairways_1 greens_1 putts_1 score_2 fairways_2 greens_2 putts_2 score_3 fairways_3 greens_3 putts_3 score_4 fairways_4 greens_4 putts_4 score_5 fairways_5 greens_5 putts_5 score_6 fairways_6 greens_6 putts_6 score_7 fairways_7 greens_7 putts_7 score_8 fairways_8 greens_8 putts_8 score_9 fairways_9 greens_9 putts_9 score_10 fairways_10 greens_10 putts_10 score_11 fairways_11 greens_11 putts_11 score_12 fairways_12 greens_12 putts_12 score_13 fairways_13 greens_13 putts_13 score_14 fairways_14 greens_14 putts_14 score_15 fairways_15 greens_15 putts_15 score_16 fairways_16 greens_16 putts_16 score_17 fairways_17 greens_17 putts_17 score_18 fairways_18 greens_18 putts_18 created_at updated_at} 
      all.each do |score|
        csv << [score.id,
        				score.user_id,
					      score.score_date,
					      score.hc,
					      score.score_1,
					      score.fairways_1,
					      score.greens_1,
					      score.putts_1,
					      score.score_2,
					      score.fairways_2,
					      score.greens_2,
					      score.putts_2,
					      score.score_3,
					      score.fairways_3,
					      score.greens_3,
					      score.putts_3,
					      score.score_4,
					      score.fairways_4,
					      score.greens_4,
					      score.putts_4,
					      score.score_5,
					      score.fairways_5,
					      score.greens_5,
					      score.putts_5,
					      score.score_6,
					      score.fairways_6,
					      score.greens_6,
					      score.putts_6,
					      score.score_7,
					      score.fairways_7,
					      score.greens_7,
					      score.putts_7,
					      score.score_8,
					      score.fairways_8,
					      score.greens_8,
					      score.putts_8,
					      score.score_9,
					      score.fairways_9,
					      score.greens_9,
					      score.putts_9,
					      score.score_10,
					      score.fairways_10,
					      score.greens_10,
					      score.putts_10,
					      score.score_11,
					      score.fairways_11,
					      score.greens_11,
					      score.putts_11,
					      score.score_12,
					      score.fairways_12,
					      score.greens_12,
					      score.putts_12,
					      score.score_13,
					      score.fairways_13,
					      score.greens_13,
					      score.putts_13,
					      score.score_14,
					      score.fairways_14,
					      score.greens_14,
					      score.putts_14,
					      score.score_15,
					      score.fairways_15,
					      score.greens_15,
					      score.putts_15,
					      score.score_16,
					      score.fairways_16,
					      score.greens_16,
					      score.putts_16,
					      score.score_17,
					      score.fairways_17,
					      score.greens_17,
					      score.putts_17,
					      score.score_18,
					      score.fairways_18,
					      score.greens_18,
					      score.putts_18,
					    	score.created_at,
					    	score.updated_at]
      end
    end
  end
end